name: DevSecOps END to END Pipeline

on:   
  workflow_dispatch:


jobs:

  code-quality:
    uses: ./.github/workflows/code-quality.yaml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yaml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yaml

  docker-scan:
    uses: ./.github/workflows/docker-lint.yaml

  build:
    needs: [code-quality, secrets-scan, docker-scan, dependency-scan]
    uses: ./.github/workflows/docker build and push.yaml
    secrets:  inherit

  trivy-scan:
    needs: [build]
    uses: ./.github/workflows/image-scan.yaml
    secrets: inherit


#  deployToServer:
#    needs: [trivy-scan]
#    uses: ./.github/workflows/deploy-to-server.yaml
#    secrets: inherit
