#scan the Dockerfile for issues and CVEs
# Uses Hadolint


name: Docker lint

on:
  workflow_call:


jobs:
  validate-dockerfile:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
